[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
healthcheckRetries = 5
restartPolicyType = "on_failure" 
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
