/**
 * Active DART (Deep-ocean Assessment and Reporting of Tsunamis) Network
 * 
 * This file is AUTO-GENERATED by scripts/update-dart-stations.ts
 * Do not edit manually - changes will be overwritten!
 * 
 * Data Source: NOAA NDBC activestations.xml
 * Last Updated: 2025-11-10
 * Total Stations: 50
 * 
 * Update Process:
 * - Runs automatically during: pnpm build
 * - Manual update: pnpm update-dart-stations
 * - Fetches stations with dart="y" from NOAA
 */

export type DartStationStatus = 'online' | 'offline' | 'detecting'

export type DartStationData = {
  id: string
  name: string
  lat: number
  lon: number
  region: string
  status: DartStationStatus
}

export const DART_STATIONS: DartStationData[] = [
  {
    "id": "21413",
    "name": "SOUTHEAST TOKYO - 700NM ESE of Tokyo, JP",
    "lat": 30.487,
    "lon": 152.124,
    "region": "Western Pacific",
    "status": "online"
  },
  {
    "id": "21414",
    "name": " AMCHITKA - 170 NM South of Amchitka, AK",
    "lat": 48.97,
    "lon": 178.165,
    "region": "Western Pacific (Japan)",
    "status": "online"
  },
  {
    "id": "21415",
    "name": "ATTU - 175 NM South of Attu, AK",
    "lat": 50.12,
    "lon": 171.867,
    "region": "Western Pacific (Japan)",
    "status": "online"
  },
  {
    "id": "21416",
    "name": "KAMCHATKA PENINSULA - 240NM SE of Kamchatka Peninsula, RU ",
    "lat": 48.126,
    "lon": 163.355,
    "region": "Western Pacific (Japan)",
    "status": "online"
  },
  {
    "id": "21419",
    "name": "KURIL ISLANDS - 209NM SE of Kuril Is. ",
    "lat": 44.401,
    "lon": 155.653,
    "region": "Western Pacific (Japan)",
    "status": "online"
  },
  {
    "id": "21420",
    "name": "SOUTHEAST MIYAZAKI - 260NM Southeast of Miyazaki",
    "lat": 28.98,
    "lon": 134.973,
    "region": "Western Pacific",
    "status": "online"
  },
  {
    "id": "23223",
    "name": "Bay of Bengal",
    "lat": 17.333,
    "lon": 89.483,
    "region": "Indian Ocean",
    "status": "online"
  },
  {
    "id": "23228",
    "name": "Arabian Sea",
    "lat": 20.764,
    "lon": 65.284,
    "region": "Indian Ocean",
    "status": "online"
  },
  {
    "id": "23401",
    "name": "BAY OF BENGAL - 600 NM WNW of Phuket, Thailand",
    "lat": 8.86,
    "lon": 88.55,
    "region": "Indian Ocean",
    "status": "online"
  },
  {
    "id": "23461",
    "name": "ANDAMAN SEA - 180 NM NW of Phuket, Thailand",
    "lat": 9.534,
    "lon": 95.669,
    "region": "Indian Ocean",
    "status": "online"
  },
  {
    "id": "32402",
    "name": "180 NM  West of Caldera, Chile",
    "lat": -26.743,
    "lon": -73.983,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "32403",
    "name": "91NM West of Antofagasta, Chile",
    "lat": -23.163,
    "lon": -72.037,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "32404",
    "name": "120 NM NW of Valparaiso",
    "lat": -32.13,
    "lon": -73.797,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "32413",
    "name": "NORTHWEST LIMA - 1000 NM WNW of Lima, Peru",
    "lat": -7.432,
    "lon": -93.464,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "34420",
    "name": "119NM NW of Concepcion, Chile",
    "lat": -35.758,
    "lon": -75.243,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "41420",
    "name": "NORTH SANTO DOMINGO - 328NM NNE of Santo Domingo, DO",
    "lat": 23.433,
    "lon": -67.386,
    "region": "Caribbean",
    "status": "online"
  },
  {
    "id": "41425",
    "name": "SOUTHWEST BERMUDA - 200 NM SSW of Hamilton, Bermuda",
    "lat": 28.639,
    "lon": -65.774,
    "region": "Caribbean",
    "status": "online"
  },
  {
    "id": "42407",
    "name": "SOUTH PUERTO RICO - 230 NM Southwest of San Juan, PR",
    "lat": 15.276,
    "lon": -68.191,
    "region": "Caribbean",
    "status": "online"
  },
  {
    "id": "43412",
    "name": "SOUTHWEST MANZANILLO - 240 NM SW of Manzanillo, MX",
    "lat": 16.02,
    "lon": -107,
    "region": "Eastern Pacific",
    "status": "online"
  },
  {
    "id": "43413",
    "name": "SOUTH ACAPULCO - 360NM South of Acapulco, MX",
    "lat": 10.927,
    "lon": -100.012,
    "region": "Eastern Pacific",
    "status": "online"
  },
  {
    "id": "44402",
    "name": "SOUTHEAST BLOCK CANYON - 130 NM SE of Fire Island, NY",
    "lat": 39.314,
    "lon": -70.717,
    "region": "Caribbean",
    "status": "online"
  },
  {
    "id": "44403",
    "name": "SABLE ISLAND BANK - 437 NM E of Boston, MA",
    "lat": 41.928,
    "lon": -61.664,
    "region": "Caribbean",
    "status": "online"
  },
  {
    "id": "46403",
    "name": "SOUTHEAST SHUMAGIN ISLAND - 186 NM SE of Shumagin Is, AK",
    "lat": 52.654,
    "lon": -156.813,
    "region": "Alaska & Aleutians",
    "status": "online"
  },
  {
    "id": "46404",
    "name": "WEST ASTORIA - 230 NM West of Astoria, OR",
    "lat": 45.852,
    "lon": -128.745,
    "region": "Northern California",
    "status": "online"
  },
  {
    "id": "46407",
    "name": "NEWPORT - 210NM West of Coos Bay, OR",
    "lat": 42.704,
    "lon": -128.895,
    "region": "Northern California",
    "status": "online"
  },
  {
    "id": "46409",
    "name": "SOUTHEAST KODIAK - 210 NM SE of Kodiak, AK",
    "lat": 55.338,
    "lon": -148.575,
    "region": "Alaska & Aleutians",
    "status": "online"
  },
  {
    "id": "46410",
    "name": "SOUTH CORDOVA - 188 NM SSE of Cordova, AK",
    "lat": 57.649,
    "lon": -143.769,
    "region": "Alaska & Aleutians",
    "status": "online"
  },
  {
    "id": "46411",
    "name": "Mendocino - 150 NM West of  Mendocino Bay, CA",
    "lat": 39.337,
    "lon": -127.04,
    "region": "Southern California",
    "status": "online"
  },
  {
    "id": "46413",
    "name": "SOUTH-SOUTHEAST ADAK - 243 NM SSE of Adak Island, AK",
    "lat": 48.045,
    "lon": -173.897,
    "region": "Pacific Northwest",
    "status": "online"
  },
  {
    "id": "46414",
    "name": "SOUTHEAST CHIRIKOF - 165 NM SE of Chirikof Island, AK",
    "lat": 53.756,
    "lon": -152.456,
    "region": "Alaska & Aleutians",
    "status": "online"
  },
  {
    "id": "46416",
    "name": "WEST VANCOUVER - 442NM West of Vancouver, BC, Canada",
    "lat": 49.939,
    "lon": -134.427,
    "region": "Pacific Northwest",
    "status": "online"
  },
  {
    "id": "46419",
    "name": "NORTHWEST SEATTLE - 300 NM WNW of Seattle, WA",
    "lat": 48.815,
    "lon": -129.623,
    "region": "Pacific Northwest",
    "status": "online"
  },
  {
    "id": "51407",
    "name": "HAWAII - 34NM West of Kailua-Kona, HI",
    "lat": 19.53,
    "lon": -156.601,
    "region": "Eastern Pacific",
    "status": "online"
  },
  {
    "id": "51425",
    "name": "NORTHWEST APIA - 370 NM NW of Apia, Samoa",
    "lat": -9.511,
    "lon": -176.258,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "52402",
    "name": "SOUTHEAST SAIPAN - 540NM ESE of Saipan",
    "lat": 11.928,
    "lon": 153.876,
    "region": "Atlantic Ocean",
    "status": "online"
  },
  {
    "id": "52403",
    "name": "NORTH MANUS - 345NM North of Manus Is , New Guinea",
    "lat": 4.018,
    "lon": 145.628,
    "region": "Atlantic Ocean",
    "status": "online"
  },
  {
    "id": "52405",
    "name": "SOUTH PHILIPPINE SEA -725 NM West of Agana, Guam",
    "lat": 12.992,
    "lon": 132.232,
    "region": "Atlantic Ocean",
    "status": "online"
  },
  {
    "id": "52406",
    "name": "NORTHEAST SOLOMON - 370NM NE of Guadalcanal",
    "lat": -5.374,
    "lon": 164.99,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "5401000",
    "name": "NZC - Offshore Gisborne Hikurangi",
    "lat": -38.2,
    "lon": -179.797,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "5401003",
    "name": "NZG - Offshore Tongatapu Tonga",
    "lat": -23.352,
    "lon": -173.402,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "5401004",
    "name": "NZH - Offshore Niue Tonga",
    "lat": -20.088,
    "lon": -171.863,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "5401005",
    "name": "NZI - Offshore Samoa Tonga",
    "lat": -16.889,
    "lon": -171.191,
    "region": "Southeast Pacific",
    "status": "online"
  },
  {
    "id": "5501002",
    "name": "NZA - Offshore Wellington Hikurangi",
    "lat": -42.371,
    "lon": 176.911,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "5501004",
    "name": "NZD - Offshore Bay of Plenty Kermadec",
    "lat": -36.1,
    "lon": 178.604,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "5501005",
    "name": "NZJ - Offshore Norfolk Island New Hebrides",
    "lat": -26.667,
    "lon": 163.955,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "5501006",
    "name": "NZK - Offshore New Caledonia New Hebrides",
    "lat": -24.309,
    "lon": 169.499,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "55012",
    "name": "Coral Sea 1     -     1285km ENE of Townsville",
    "lat": -15.664,
    "lon": 158.453,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "55015",
    "name": "TASMAN SEA 1     -     1110km ESE of Hobart",
    "lat": -46.956,
    "lon": 160.343,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "55023",
    "name": "Coral Sea 2     -     870km NE of Townsville",
    "lat": -14.715,
    "lon": 153.537,
    "region": "South Pacific",
    "status": "online"
  },
  {
    "id": "56003",
    "name": "Indian Ocean 2     -     630km NNE of Dampier",
    "lat": -15.019,
    "lon": 118.073,
    "region": "South Pacific",
    "status": "online"
  }
]

/**
 * Get network statistics
 */
export function getNetworkStats() {
  const online = DART_STATIONS.filter(s => s.status === 'online').length
  const detecting = DART_STATIONS.filter(s => s.status === 'detecting').length
  const offline = DART_STATIONS.filter(s => s.status === 'offline').length
  const regions = new Set(DART_STATIONS.map(s => s.region)).size
  
  return {
    total: DART_STATIONS.length,
    online,
    detecting,
    offline,
    regions,
    health: Math.round((online / DART_STATIONS.length) * 100)
  }
}
