#!/usr/bin/env tsx
/**
 * DART Stations Auto-Update Script
 * 
 * Fetches the latest active DART stations from NOAA's XML API
 * and generates an updated dart-stations.ts file.
 * 
 * Run automatically during build or manually via:
 * pnpm update-dart-stations
 */

import { parseString } from 'xml2js'
import { promisify } from 'util'
import fs from 'fs/promises'
import path from 'path'

const parseXML = promisify(parseString)

type NOAAStation = {
  $: {
    id: string
    lat: string
    lon: string
    name: string
    owner: string
    pgm: string
    dart: string
  }
}

async function fetchActiveDartStations() {
  console.log('📡 Fetching active DART stations from NOAA...')
  
  const response = await fetch('https://www.ndbc.noaa.gov/activestations.xml', {
    headers: { 'User-Agent': 'TsunamiMonitor/1.0' }
  })
  
  if (!response.ok) {
    throw new Error(`Failed to fetch: ${response.status}`)
  }
  
  const xml = await response.text()
  const result = await parseXML(xml) as any
  
  const stations = result.stations.station
    .filter((s: NOAAStation) => s.$.dart === 'y')
    .map((s: NOAAStation) => ({
      id: s.$.id,
      name: s.$.name || `DART ${s.$.id}`,
      lat: parseFloat(s.$.lat),
      lon: parseFloat(s.$.lon),
      region: determineRegion(parseFloat(s.$.lat), parseFloat(s.$.lon)),
      status: 'online' as const
    }))
    .sort((a: any, b: any) => a.id.localeCompare(b.id))
  
  console.log(`✅ Found ${stations.length} active DART stations`)
  return stations
}

function determineRegion(lat: number, lon: number): string {
  // North Pacific (Alaska & West Coast)
  if (lat > 30 && lon < -110) {
    if (lat > 52) return 'Alaska & Aleutians'
    if (lat > 46) return 'Pacific Northwest'
    if (lat > 40) return 'Northern California'
    return 'Southern California'
  }
  
  // Western Pacific (Asia)
  if (lat > 20 && lon > 120) {
    if (lat > 35) return 'Western Pacific (Japan)'
    return 'Western Pacific'
  }
  
  // South Pacific
  if (lat < 0 && lon > 100) return 'South Pacific'
  if (lat < 0 && lon < -70) return 'Southeast Pacific'
  
  // Indian Ocean
  if (lon > 60 && lon < 100) return 'Indian Ocean'
  
  // Caribbean & Atlantic
  if (lon > -90 && lon < -50 && lat > 10) return 'Caribbean'
  if (lon > -50 && lat > 0) return 'Atlantic Ocean'
  
  // Eastern Pacific
  if (lon < -80) return 'Eastern Pacific'
  
  return 'Pacific Ocean'
}

async function generateTypeScriptFile(stations: any[]) {
  const timestamp = new Date().toISOString().split('T')[0]
  
  const content = `/**
 * Active DART (Deep-ocean Assessment and Reporting of Tsunamis) Network
 * 
 * This file is AUTO-GENERATED by scripts/update-dart-stations.ts
 * Do not edit manually - changes will be overwritten!
 * 
 * Data Source: NOAA NDBC activestations.xml
 * Last Updated: ${timestamp}
 * Total Stations: ${stations.length}
 * 
 * Update Process:
 * - Runs automatically during: pnpm build
 * - Manual update: pnpm update-dart-stations
 * - Fetches stations with dart="y" from NOAA
 */

export type DartStationStatus = 'online' | 'offline' | 'detecting'

export type DartStationData = {
  id: string
  name: string
  lat: number
  lon: number
  region: string
  status: DartStationStatus
}

export const DART_STATIONS: DartStationData[] = ${JSON.stringify(stations, null, 2)}

/**
 * Get network statistics
 */
export function getNetworkStats() {
  const online = DART_STATIONS.filter(s => s.status === 'online').length
  const detecting = DART_STATIONS.filter(s => s.status === 'detecting').length
  const offline = DART_STATIONS.filter(s => s.status === 'offline').length
  const regions = new Set(DART_STATIONS.map(s => s.region)).size
  
  return {
    total: DART_STATIONS.length,
    online,
    detecting,
    offline,
    regions,
    health: Math.round((online / DART_STATIONS.length) * 100)
  }
}
`
  
  const filePath = path.join(process.cwd(), 'lib/data/dart-stations.ts')
  await fs.writeFile(filePath, content, 'utf-8')
  
  console.log(`✅ Generated ${filePath}`)
  console.log(`📊 ${stations.length} active DART stations`)
}

async function main() {
  try {
    const stations = await fetchActiveDartStations()
    await generateTypeScriptFile(stations)
    console.log('✅ DART stations updated successfully!')
  } catch (error) {
    console.error('❌ Failed to update DART stations:', error)
    console.error('⚠️  Using existing dart-stations.ts as fallback')
    process.exit(0) // Don't fail the build, use existing data
  }
}

main()
